defaultBaseImage: mcr.microsoft.com/cbl-mariner/distroless/base:2.0-nonroot

builds:
- id: reports-server-fips
  main: .
  ldflags:
  - '{{ if index .Env "LD_FLAGS" }}{{ .Env.LD_FLAGS }}{{ end }}'
  flags:
  - -tags
  - fips

# TODO: export a variable and print in the code to check if that is picked up or not
