apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: reports-server-cluster
  namespace: reports-server
spec:
  instances: 3
  primaryUpdateStrategy: unsupervised
  bootstrap:
    initdb:
      database: reportsdb
  storage:
    size: 10Gi
