name: Create Publish and Sign Docker Image for FIPS Compliance

on:
  workflow_call:
    inputs:
      publish_command:
        required: true
        type: string
      digest_command:
        required: true
        type: string
      image_name:
        required: true
        type: string
      tag:
        required: true
        type: string
      main:
        type: string
    secrets:
      registry_username:
        required: true
      registry_password:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
    - name: Checkout release
      if: ${{ inputs.tag == 'release'}}
      uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2.4.0
      with:
        fetch-depth: 0

    - name: Log into ghcr.io
      uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@27d0a4f181a40b142cce983c5393082c365d1480 # v1.2.0

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@c47758b77c9736f4b2ef4073d4d51994fabfe349 #v3.7.1
      id: buildx
      with:
        install: true

    - name: Set Version
      if: ${{ inputs.tag == 'release'}}
      run: |
        echo "KYVERNO_VERSION=$(git describe --match "v[0-9]*" --tags $(git rev-list --tags --max-count=1))" >> $GITHUB_ENV

    - name: Docker release-images publish
      if: ${{inputs.tag == 'release' || inputs.tag == 'image' }}
      run: make ${{inputs.publish_command}} FIPS_ENABLED=1

